---
title: "BM_hw5_jh4324"
author: "Jiying Han"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(arsenal) 
library(stats)
library(BSDA)
library(broom)
```


Read and tidy the dataset 
```{r}
antibody_df = 
  read.csv("./Antibodies copy.csv") %>% 
  filter(Smell != "Unanswered/Others") %>% 
  mutate(
    AgeCategory = as.factor(AgeCategory),
    Antibody_IgM = as.numeric(Antibody_IgM),
    Smell = as.factor(Smell),
    Gender = as.factor(Gender)
  ) %>% 
   drop_na(Antibody_IgM,Smell)


# justify whether it is tie
distinct_number = antibody_df %>% 
  distinct(Antibody_IgM)
total_number = nrow(antibody_df)
# there is 166 distinct number after combined two groups, however, the total number of subjects in two groups is 259. Thus, there is tie.



norm_vec = 
  antibody_df %>% 
  filter(Smell == "Normal") %>% 
  select(Antibody_IgM)
  
alter_vec = 
  antibody_df %>% 
  filter(Smell == "Altered") %>% 
  select(Antibody_IgM) 


n1 = nrow(norm_vec)
n2 = nrow(alter_vec)
t1s = (1/2)*n1*(n1+1) 
t1h = n1*n2+(1/2)*n1*(n1+1)
et1 = (1/2)*n1*(n1+n2+1) 

par(mfrow=c(2,2))
hist(norm_vec$Antibody_IgM, xlab="Antibody_IgM", freq=T, main="Normal smell patients' antibody")
hist(alter_vec$Antibody_IgM, xlab="Antibody_IgM", freq=T, main="Altered smell patients' antibody")

qqnorm(norm_vec$Antibody_IgM, col=2, pch=19, cex=1.5)
qqline(norm_vec$Antibody_IgM, col = 1,lwd=2,lty=2)

qqnorm(alter_vec$Antibody_IgM, col=2, pch=19, cex=1.5)
qqline(alter_vec$Antibody_IgM, col = 1,lwd=2,lty=2)


res = wilcox.test(norm_vec$Antibody_IgM, alter_vec$Antibody_IgM, mu=0)
res$statistic = res$statistic + n1*(n1+1)/2
res

```



# Problem 3

```{r}
gpa_df =
  read.csv("./GPA.csv") %>% 
  janitor::clean_names()

# a scatter plot with regression line overlaid
gpa_df %>% 
  ggplot(aes(x = act,y = gpa))+ geom_point(color = "blue") +
  geom_smooth(method='lm', se=TRUE, color='red') +
  theme_bw(base_size=20) +
  labs(x="Student’s ACT score", y="Student’s GPA at the end of the freshman year ")


# regression test
reg_stu = lm(gpa~act,gpa_df)
summary(reg_stu)

t_stat = (0.03883-0)/0.01277
n = nrow(gpa_df)
qt(0.975,118)

# 95% CIs for slope
mean(gpa_df$act)
confint(reg_stu,level=0.95)

# 95% CIs of mean freshman GPA for students whose ACT test score is 28 using predict
new.act = tibble(act = c(28))

predict(reg_stu, newdata = new.act, interval = "confidence", level = 0.95)
predict(reg_stu, newdata = new.act, interval = "prediction", level = 0.95)

```



